/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BRS;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Saqib Hussain
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    AdminController ac1=new AdminController();
    public AdminView() {
        initComponents();
        getContentPane().setBackground(new Color(0,69,114));
        this.bCPassword.setEnabled(false);
        this.bPrint.setEnabled(false);
        this.bLock.setEnabled(false);
        this.bInquiry.setEnabled(false);
        this.ButtonsPane.setVisible(false);
        this.bClSeats.setEnabled(false);
        this.bRTicket.setEnabled(false);
        this.PaneInquiry.setVisible(false);
        this.bclRecord.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonsPane = new javax.swing.JLayeredPane();
        bInquiry = new javax.swing.JButton();
        bClSeats = new javax.swing.JButton();
        bCPassword = new javax.swing.JButton();
        bclRecord = new javax.swing.JButton();
        bMenu = new javax.swing.JButton();
        bLock = new javax.swing.JButton();
        bRTicket = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        bSubmit = new javax.swing.JButton();
        bMenu1 = new javax.swing.JButton();
        PaneInquiry = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        txtTicID = new javax.swing.JTextField();
        bSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaT = new javax.swing.JTextArea();
        bBack = new javax.swing.JButton();
        bPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administrator");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(0, 16, 42));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saqib Hussain\\Downloads\\BlueBird.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Blue Bird Travels");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        ButtonsPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bInquiry.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bInquiry.setText("Booking Inquiry");
        bInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInquiryActionPerformed(evt);
            }
        });

        bClSeats.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bClSeats.setText("Clear Seats");
        bClSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClSeatsActionPerformed(evt);
            }
        });

        bCPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bCPassword.setText("ChangePassword");
        bCPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCPasswordActionPerformed(evt);
            }
        });

        bclRecord.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bclRecord.setText("Clear Record");
        bclRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclRecordActionPerformed(evt);
            }
        });

        bMenu.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bMenu.setText("MainMenu");
        bMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuActionPerformed(evt);
            }
        });

        bLock.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bLock.setText("Lock Screen");
        bLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLockActionPerformed(evt);
            }
        });

        bRTicket.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bRTicket.setText("Reset Ticket # ");
        bRTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bRTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPaneLayout = new javax.swing.GroupLayout(ButtonsPane);
        ButtonsPane.setLayout(ButtonsPaneLayout);
        ButtonsPaneLayout.setHorizontalGroup(
            ButtonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ButtonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ButtonsPaneLayout.createSequentialGroup()
                            .addComponent(bMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(bclRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ButtonsPaneLayout.createSequentialGroup()
                            .addComponent(bCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(bRTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(13, 13, 13)
                .addGroup(ButtonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bClSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLock, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonsPaneLayout.setVerticalGroup(
            ButtonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLock, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bclRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(bInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(ButtonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bClSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonsPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bCPassword, bClSeats, bInquiry, bMenu, bclRecord});

        ButtonsPane.setLayer(bInquiry, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ButtonsPane.setLayer(bClSeats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ButtonsPane.setLayer(bCPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ButtonsPane.setLayer(bclRecord, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ButtonsPane.setLayer(bMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ButtonsPane.setLayer(bLock, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ButtonsPane.setLayer(bRTicket, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane1.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Admin Password:");

        bSubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        bMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bMenu1.setText("MainMenu");
        bMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bMenu1)
                        .addGap(18, 18, 18)
                        .addComponent(bSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMenu1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bSubmit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bMenu1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PaneInquiry.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Ticket-ID:");

        txtTicID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTicIDActionPerformed(evt);
            }
        });

        bSearch.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bSearch.setText("Search");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        AreaT.setEditable(false);
        AreaT.setBackground(new java.awt.Color(0, 69, 114));
        AreaT.setColumns(20);
        AreaT.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        AreaT.setForeground(new java.awt.Color(255, 255, 255));
        AreaT.setRows(5);
        AreaT.setBorder(null);
        jScrollPane1.setViewportView(AreaT);

        bBack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        bPrint.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bPrint.setText("Print");

        javax.swing.GroupLayout PaneInquiryLayout = new javax.swing.GroupLayout(PaneInquiry);
        PaneInquiry.setLayout(PaneInquiryLayout);
        PaneInquiryLayout.setHorizontalGroup(
            PaneInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneInquiryLayout.createSequentialGroup()
                .addGroup(PaneInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bPrint)
                    .addGroup(PaneInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PaneInquiryLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(PaneInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PaneInquiryLayout.createSequentialGroup()
                                    .addComponent(bBack)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bSearch))
                                .addGroup(PaneInquiryLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(48, 48, 48)
                                    .addComponent(txtTicID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(PaneInquiryLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        PaneInquiryLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bBack, bSearch});

        PaneInquiryLayout.setVerticalGroup(
            PaneInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneInquiryLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(PaneInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTicID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaneInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSearch)
                    .addComponent(bBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPrint))
        );
        PaneInquiry.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneInquiry.setLayer(txtTicID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneInquiry.setLayer(bSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneInquiry.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneInquiry.setLayer(bBack, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneInquiry.setLayer(bPrint, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ButtonsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(PaneInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(PaneInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(517, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void bInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInquiryActionPerformed
        //this.ButtonsPane.setVisible(false);
        this.PaneInquiry.setVisible(true);
        this.bClSeats.setEnabled(false);
        this.bMenu.setEnabled(false);
        this.bCPassword.setEnabled(false);
        this.bInquiry.setEnabled(false);
        this.bRTicket.setEnabled(false);
        this.bclRecord.setEnabled(false);
        this.bLock.setEnabled(false);
        this.txtTicID.setText("");
        this.AreaT.setText("");
        
    }//GEN-LAST:event_bInquiryActionPerformed

    private void bclRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclRecordActionPerformed
            
       ac1.ClearPassengersRecords(JOptionPane.showConfirmDialog(this, "Are you Sure You Want to delete all Data"));
       
    }//GEN-LAST:event_bclRecordActionPerformed

    private void bClSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClSeatsActionPerformed
        // TODO add your handling code here:
        ac1.clearSeatsCompletely(JOptionPane.showConfirmDialog(this, "Are you Sure You Want to Reset Allocated Seats"));
    }//GEN-LAST:event_bClSeatsActionPerformed

    private void bCPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCPasswordActionPerformed
        // TODO add your handling code here:
        String p=JOptionPane.showInputDialog(this,"Enter New Password");
        if((p!=null)&&(!p.equals(""))){
            ac1.ChangeCurrentPassword(p);
            JOptionPane.showMessageDialog(this,"Password Successfully Changed");
        }
        
        else{
            if(p!=null){
            JOptionPane.showMessageDialog(this,"You Cannot leave Password field Blank");
            }
        }
    }//GEN-LAST:event_bCPasswordActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        // TODO add your handling code here:
       
        if(ac1.checkAdminPassword(this.txtPass.getText())==true){
            JOptionPane.showMessageDialog(this,"\t\tAccess Granted");
            this.bCPassword.setEnabled(true);
            this.bInquiry.setEnabled(true);
            this.bClSeats.setEnabled(true);
            this.bRTicket.setEnabled(true);
            this.bclRecord.setEnabled(true);
            this.bMenu1.setVisible(false);
            this.bLock.setEnabled(true);
            this.ButtonsPane.setVisible(true);
            this.jLayeredPane1.setVisible(false);
            this.txtPass.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this,"\t\tAccess Denied");
            this.txtPass.setText("");
        }
    }//GEN-LAST:event_bSubmitActionPerformed

    private void bMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuActionPerformed
        // TODO add your handling code here:
        MainMenu m1=new MainMenu();
        m1.show();
        this.dispose();
    }//GEN-LAST:event_bMenuActionPerformed

    private void bLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLockActionPerformed
        // TODO add your handling code here:
        this.ButtonsPane.setVisible(false);
        this.jLayeredPane1.setVisible(true);
    }//GEN-LAST:event_bLockActionPerformed

    private void bRTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRTicketActionPerformed
        // TODO add your handling code here:
        ac1.resetTicketNumberSequence(JOptionPane.showConfirmDialog(this, "Are you Sure You Want to Reset Ticket Numbers"));
    }//GEN-LAST:event_bRTicketActionPerformed

    private void bMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenu1ActionPerformed
        // TODO add your handling code here:
        MainMenu m1=new MainMenu();
        m1.show();
        this.dispose();
    }//GEN-LAST:event_bMenu1ActionPerformed

    private void txtTicIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicIDActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        // TODO add your handling code here:
        ac1.BookingInquiry(this.txtTicID.getText());
        if(ac1.getFound()==1){
            this.AreaT.setText("Ticket Number:\t"+this.txtTicID.getText()+"\nRoute:\t\t"+ac1.getRoute());
            this.AreaT.setText(AreaT.getText()+"\nBus-ID:\t\t"+ac1.getBusID()+"\nSeats#\t\t"+ac1.getSeatsID()+"\nFare:\t\t"+ac1.getFare());
            this.AreaT.setText(AreaT.getText()+"\nDate:\t\t"+ac1.getDate()+"\nDepartureTime:\t"+ac1.getDepartTime());
            this.AreaT.setText(AreaT.getText()+"\n...............................................................");
            this.AreaT.setText(AreaT.getText()+"\nName:\t\t"+ac1.getName()+"\nCnic:\t\t"+ac1.getCnic());
            this.AreaT.setText(AreaT.getText()+"\nPhone#\t\t"+ac1.getPhone());
            this.AreaT.setText(AreaT.getText()+"\nBooking-Date:\t\t"+ac1.getBookingDate()+"\nBooking-Time:\t\t"+ac1.getBookingTime()); 
            this.bPrint.setEnabled(true);

        }
        else{
            JOptionPane.showMessageDialog(this,"Ticket Number Not Found");
            this.txtTicID.setText("");
            this.AreaT.setText("");
            this.bPrint.setEnabled(false);
        }
    }//GEN-LAST:event_bSearchActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        // TODO add your handling code here:
        this.PaneInquiry.setVisible(false);
        this.bClSeats.setEnabled(true);
        this.bMenu.setEnabled(true);
        this.bCPassword.setEnabled(true);
        this.bInquiry.setEnabled(true);
        this.bRTicket.setEnabled(true);
        this.bclRecord.setEnabled(true);
        this.bLock.setEnabled(true);
    }//GEN-LAST:event_bBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaT;
    private javax.swing.JLayeredPane ButtonsPane;
    private javax.swing.JLayeredPane PaneInquiry;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bCPassword;
    private javax.swing.JButton bClSeats;
    private javax.swing.JButton bInquiry;
    private javax.swing.JButton bLock;
    private javax.swing.JButton bMenu;
    private javax.swing.JButton bMenu1;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bRTicket;
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bSubmit;
    private javax.swing.JButton bclRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTicID;
    // End of variables declaration//GEN-END:variables
}
