/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BRS;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Saqib Hussain
 */
public class LocationView extends javax.swing.JFrame {

    /**
     * Creates new form Book
     */
    public LocationView() {
        initComponents();
        getContentPane().setBackground(new Color(0,69,114));
        bNext.setEnabled(false);
        
        this.jLayeredPane2.setVisible(false);
        this.bCleartxt.setEnabled(false);
        this.LabelID.setVisible(false);
        this.txtID.setVisible(false);
        
        
    }
    int digitsCount=0;
    LocationController Lc1=new LocationController();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        bCleartxt = new javax.swing.JButton();
        bNext = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSubmit = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbFrom = new javax.swing.JComboBox();
        cbTo = new javax.swing.JComboBox();
        bSubmit = new javax.swing.JButton();
        bBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Blue Bird");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 730));

        jLabel1.setForeground(new java.awt.Color(0, 16, 42));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saqib Hussain\\Downloads\\BlueBird.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Blue Bird Travels");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(300, 177));

        bCleartxt.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bCleartxt.setText("Clear");
        bCleartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCleartxtActionPerformed(evt);
            }
        });

        bNext.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bNext.setText("Next");
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });

        LabelID.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        LabelID.setForeground(new java.awt.Color(255, 255, 255));
        LabelID.setText("Enter Bus Id You'd like to Book:");

        txtAreaSubmit.setEditable(false);
        txtAreaSubmit.setBackground(new java.awt.Color(0, 69, 114));
        txtAreaSubmit.setColumns(20);
        txtAreaSubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtAreaSubmit.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaSubmit.setRows(5);
        txtAreaSubmit.setBorder(null);
        txtAreaSubmit.setPreferredSize(new java.awt.Dimension(300, 155));
        jScrollPane1.setViewportView(txtAreaSubmit);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(LabelID)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(bCleartxt)
                        .addGap(18, 18, 18)
                        .addComponent(bNext))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNext)
                    .addComponent(bCleartxt))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(bCleartxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bNext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(LabelID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Location");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To:");

        cbFrom.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cbFrom.setMaximumRowCount(10);
        cbFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islamabad", "Lahore", "Peshawar", "Faislabad", "Swat" }));
        cbFrom.setToolTipText("");
        cbFrom.setActionCommand("");
        cbFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFromActionPerformed(evt);
            }
        });
        cbFrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbFromKeyPressed(evt);
            }
        });

        cbTo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cbTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islamabad", "Lahore", "Peshawar", "Faislabad", "Swat" }));
        cbTo.setSelectedIndex(1);
        cbTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToActionPerformed(evt);
            }
        });

        bSubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        bBack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bSubmit))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSubmit)
                    .addComponent(bBack))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbFrom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbTo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bSubmit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cbFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFromActionPerformed
        this.bNext.setEnabled(false);
        if(String.valueOf(cbFrom.getSelectedIndex()).equals(String.valueOf(cbTo.getSelectedIndex()))){
            this.bSubmit.setEnabled(false);
            this.bNext.setEnabled(false);
            this.txtAreaSubmit.setText("Invalid Locations Selected\n");
        }
        else{
            this.bSubmit.setEnabled(true);
            this.txtAreaSubmit.setText("");
        }
        
    }//GEN-LAST:event_cbFromActionPerformed

    private void cbToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToActionPerformed
        this.bNext.setEnabled(false);
        if(String.valueOf(cbFrom.getSelectedIndex()).equals(String.valueOf(cbTo.getSelectedIndex()))){
            this.bSubmit.setEnabled(false);
            this.bNext.setEnabled(false);
            this.txtAreaSubmit.setText("\n");
        }
        else{
            this.bSubmit.setEnabled(true);
            this.txtAreaSubmit.setText("");
        }
    }//GEN-LAST:event_cbToActionPerformed

    private void cbFromKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbFromKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFromKeyPressed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        this.LabelID.setVisible(true);
        this.txtID.setVisible(true);
        this.bCleartxt.setEnabled(true);
        this.jLayeredPane2.setVisible(true);
        Lc1.setIndex(cbFrom.getSelectedIndex(), cbTo.getSelectedIndex());
         bNext.setEnabled(true);
        Lc1.setFirstBus();
        
        this.txtAreaSubmit.setText("\tTotal Buses On Route: 02\n-------------------------------------------------------------------------");
        this.txtAreaSubmit.setText(txtAreaSubmit.getText()+"\nBus ID:\t\t"+String.valueOf(Lc1.getBusId())+"\n");
        this.txtAreaSubmit.setText(txtAreaSubmit.getText()+"Meal:\t\t"+Lc1.getAcStatus()+"\n"+"Fare:\t\t"+String.valueOf(Lc1.getFare()));
        this.txtAreaSubmit.setText(txtAreaSubmit.getText()+"\nDeparture:\t\t"+Lc1.getDep()+"\nArrival:\t\t"+Lc1.getArr());
        Lc1.setSecondBus();
        this.txtAreaSubmit.setText(txtAreaSubmit.getText()+"\n-------------------------------------------------------------------------");
        this.txtAreaSubmit.setText(txtAreaSubmit.getText()+"\nBus ID:\t\t"+String.valueOf(Lc1.getBusId())+"\n");
        this.txtAreaSubmit.setText(txtAreaSubmit.getText()+"Meal:\t\t"+Lc1.getAcStatus()+"\n"+"Fare:\t\t"+String.valueOf(Lc1.getFare()));
        this.txtAreaSubmit.setText(txtAreaSubmit.getText()+"\nDeparture:\t\t"+Lc1.getDep()+"\nArrival:\t\t"+Lc1.getArr());
        
       
    }//GEN-LAST:event_bSubmitActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        // TODO add your handling code here:
        
        MainMenu m1=new MainMenu();
        m1.setVisible(true);
        this.dispose();
        //this.PaneInfo.setVisible(true);
        
    }//GEN-LAST:event_bBackActionPerformed

    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed
        if(this.txtID.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Enter Bus ID to Continue");
            this.txtID.setText("");
            this.digitsCount=0;
        }
        else{
            Lc1.setIdEntered(Integer.parseInt(this.txtID.getText()));
            Lc1.getRequestedId();


            if(Lc1.getRequestedId()!=0){
            BusView b1=new BusView();

            Lc1.saveIDRouteInfile();

            b1.show();
            b1.update();
            this.dispose();  
            }

            else{
                JOptionPane.showMessageDialog(this, "Enter a valid ID Please");
                this.txtID.setText("");
                this.digitsCount=0;
            }
        
        }
        
    }//GEN-LAST:event_bNextActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
        int k=evt.getKeyCode();
        
        if(digitsCount<3){
        if(k>=evt.VK_0&&k<=evt.VK_9){
            this.txtID.setEditable(true);
            digitsCount++;
            
        }
        else if(k>=evt.VK_NUMPAD0&&k<=evt.VK_NUMPAD9){
            this.txtID.setEditable(true);
            digitsCount++; 
        }
        else{
            this.txtID.setEditable(false);
        }
        }
        else{
            this.txtID.setEditable(false);
        }
    
    }//GEN-LAST:event_txtIDKeyPressed

    private void bCleartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCleartxtActionPerformed
        // TODO add your handling code here:
        this.txtID.setText("");
        this.digitsCount=0;
        
    }//GEN-LAST:event_bCleartxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelID;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bCleartxt;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bSubmit;
    private javax.swing.JComboBox cbFrom;
    private javax.swing.JComboBox cbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaSubmit;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
