/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BRS;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Saqib Hussain
 */
public class MapView extends javax.swing.JFrame {

    /**
     * Creates new form MapView
     */
    public MapView() {
        initComponents();
        //getContentPane().setBackground(new Color (0,69,114));
        getContentPane().setBackground(new Color(0,69,114));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        bIslLah = new javax.swing.JButton();
        bIslPes7 = new javax.swing.JButton();
        bIslPes6 = new javax.swing.JButton();
        bIslPes5 = new javax.swing.JButton();
        bIslPes4 = new javax.swing.JButton();
        bIslPes8 = new javax.swing.JButton();
        bIslPes2 = new javax.swing.JButton();
        bIslPes = new javax.swing.JButton();
        bIslPes3 = new javax.swing.JButton();
        bIslPes1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Maps");
        setPreferredSize(new java.awt.Dimension(1366, 769));

        jLabel1.setForeground(new java.awt.Color(0, 16, 42));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saqib Hussain\\Downloads\\BlueBird.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Blue Bird Travels");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bIslLah.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslLah.setText("Islamabad-Lahore");
        bIslLah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslLahActionPerformed(evt);
            }
        });

        bIslPes7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes7.setText("Peshawar-Swat");
        bIslPes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes7ActionPerformed(evt);
            }
        });

        bIslPes6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes6.setText("Faislabad-Islamabad");
        bIslPes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes6ActionPerformed(evt);
            }
        });

        bIslPes5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes5.setText("Faislabad-Peshawar");
        bIslPes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes5ActionPerformed(evt);
            }
        });

        bIslPes4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes4.setText("Lahore-Faislabad");
        bIslPes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes4ActionPerformed(evt);
            }
        });

        bIslPes8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes8.setText("Peshawar-Lahore");
        bIslPes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes8ActionPerformed(evt);
            }
        });

        bIslPes2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes2.setText("Swat-Faislabad");
        bIslPes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes2ActionPerformed(evt);
            }
        });

        bIslPes.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes.setText("Islamabad-Peshawar");
        bIslPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPesActionPerformed(evt);
            }
        });

        bIslPes3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes3.setText("Lahore-Swat");
        bIslPes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes3ActionPerformed(evt);
            }
        });

        bIslPes1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bIslPes1.setText("Swat-Islamabad");
        bIslPes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIslPes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(bIslLah, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bIslPes7, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bIslPes6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIslPes2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIslPes, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIslPes1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bIslPes8, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIslPes4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIslPes5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bIslPes3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bIslLah, bIslPes, bIslPes1, bIslPes2, bIslPes3, bIslPes4, bIslPes5, bIslPes6, bIslPes7, bIslPes8});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIslLah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bIslPes7, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIslPes6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bIslPes4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIslPes8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bIslPes2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bIslPes, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(bIslPes5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIslPes3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bIslPes1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bIslLah, bIslPes, bIslPes2, bIslPes3, bIslPes4, bIslPes6, bIslPes7, bIslPes8});

        jLayeredPane1.setLayer(bIslLah, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bIslPes1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void bIslLahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslLahActionPerformed
        // TODO add your handling code here:
        MapIsltoLah obj=new MapIsltoLah();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslLahActionPerformed

    private void bIslPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPesActionPerformed
        // TODO add your handling code here:
        MapIsltoPes obj=new MapIsltoPes();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu obj1=new MainMenu();
        obj1.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bIslPes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes1ActionPerformed
        // TODO add your handling code here:
        MapIsltoSwat obj=new MapIsltoSwat();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes1ActionPerformed

    private void bIslPes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes2ActionPerformed
        // TODO add your handling code here:
         MapSwattoFais obj=new MapSwattoFais();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes2ActionPerformed

    private void bIslPes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes3ActionPerformed
        // TODO add your handling code here:
         MapLahtoSwat obj=new MapLahtoSwat();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes3ActionPerformed

    private void bIslPes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes4ActionPerformed
        // TODO add your handling code here:
        MapLahtoFais obj=new MapLahtoFais();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes4ActionPerformed

    private void bIslPes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes5ActionPerformed
        // TODO add your handling code here:
        MapFaistoPes obj=new MapFaistoPes();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes5ActionPerformed

    private void bIslPes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes6ActionPerformed
        // TODO add your handling code here:
        MapFaistoIsl obj=new MapFaistoIsl();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes6ActionPerformed

    private void bIslPes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes7ActionPerformed
        // TODO add your handling code here:
        MapPestoSwat obj=new MapPestoSwat();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes7ActionPerformed

    private void bIslPes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIslPes8ActionPerformed
        // TODO add your handling code here:
         MapPestoLah obj=new MapPestoLah();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_bIslPes8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIslLah;
    private javax.swing.JButton bIslPes;
    private javax.swing.JButton bIslPes1;
    private javax.swing.JButton bIslPes2;
    private javax.swing.JButton bIslPes3;
    private javax.swing.JButton bIslPes4;
    private javax.swing.JButton bIslPes5;
    private javax.swing.JButton bIslPes6;
    private javax.swing.JButton bIslPes7;
    private javax.swing.JButton bIslPes8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

    private ImageIcon createImageIcon(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
